# Generated by Django 5.1 on 2024-08-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0003_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="WbtSipxSRZF3SQLeepUGDlcwX5NRSOLw",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
